### ISSUE TITLE
Outdated version

### ISSUE THREAD

**Issue by topazur** [sqlc-dev/sqlc-go#3]
This repo: `github.com/sqlc-dev/sqlc-go v1.18.1`
imports deps: `buf.build/gen/go/sqlc/sqlc/protocolbuffers/go v1.31.0-20230731215519-a0cf5310fab9.1`

but `github.com/sqlc-dev/sqlc/blob/v1.22.0/internal/plugin/codegen.pb.go` diff `buf.build/gen/go/sqlc/sqlc/protocolbuffers/go`

**Comment by topazur** [comment]
Missing OutputCopyFromFileName attribute

Can you keep it synchronized? Can facilitate the development of plugins！

Thanks！

**Comment by kyleconroy** [comment]
Fixed in https://github.com/sqlc-dev/sqlc-go/commit/c6dbb20a9c13ccf59423cbf0121b2cb9effd8e70
